# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInformation',
            fields=[
                ('name', models.CharField(max_length=90, verbose_name='Категория информационного актива')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InformationAsset',
            fields=[
                ('name', models.CharField(max_length=90, verbose_name='Наименование информационного актива')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorminformation.CategoryInformation', verbose_name='Категория информационного актива')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInformation',
            fields=[
                ('name', models.CharField(max_length=90, verbose_name='Тип информационного актива')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='informationasset',
            name='type_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorminformation.TypeInformation', verbose_name='Тип информационного актива'),
        ),
    ]
