# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sormcontrol', '0001_initial'),
        ('sorminformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationasset',
            name='information_controls',
            field=models.ManyToManyField(to='sormcontrol.Control'),
        ),
    ]
