# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sormcontrol', '0002_auto_20180314_1821'),
        ('sorminformation', '0002_informationasset_information_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationasset',
            name='information_class_controls',
            field=models.ManyToManyField(to='sormcontrol.ClassControl', verbose_name='Класс СЗИ'),
        ),
    ]
