# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('name', models.CharField(max_length=90, verbose_name='Наименование контрмеры')),
                ('type_realization', models.CharField(choices=[('O', 'Организационная реализация'), ('T', 'Техническая')], default='T', max_length=2, verbose_name='Тип реализации')),
                ('class_control', models.CharField(choices=[('6', '6 Класс'), ('5', '5 Класс'), ('4', '4 Класс'), ('No', 'Не имеет класса')], default='No', max_length=3, verbose_name='Класс СЗИ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
