# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sormcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassControl',
            fields=[
                ('name', models.CharField(max_length=90, verbose_name='Класс СЗИ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRealization',
            fields=[
                ('name', models.CharField(max_length=90, verbose_name='Тип реализации')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='control',
            name='class_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sormcontrol.ClassControl', verbose_name='Класс СЗИ'),
        ),
        migrations.AlterField(
            model_name='control',
            name='type_realization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sormcontrol.TypeRealization', verbose_name='Тип реализации'),
        ),
    ]
