# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sormcontrol', '0002_auto_20180314_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='class_control',
        ),
    ]
