# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Наименование организационной единицы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sormcompany.Company', verbose_name='Родительская организация')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Тип организационной единицы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sormcompany.TypeCompany', verbose_name='Тип организационной единицы'),
        ),
    ]
