# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sormcompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Наименование организационной единицы'),
        ),
        migrations.AlterField(
            model_name='typecompany',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Тип организационной единицы'),
        ),
    ]
