# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sormcompany', '0002_auto_20180305_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sormcompany.TypeCompany', verbose_name='Тип организационной единицы'),
        ),
    ]
