# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sormcompany', '0003_auto_20180305_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent_company',
        ),
    ]
